Feature: Add Todo List Functionality (Add, Edit, Delete)
zain-sattar/todo-list-app pull request #2
Opened 2023-06-06 10:39 UTC by zain-sattar

This pull request adds the functionality of a Todo List app, including the ability to add new todos, edit existing todos, and delete todos. The following changes have been made:

1) Implemented the logic to add a new todo to the list.
2) Implemented the functionality to edit existing todos (mark as complete).
3) Implemented the ability to delete todos from the list.

Please review this pull request and let me know if any further changes or improvements are required.

2023-06-07 13:07 UTC, danialsyed6 requested changes
your style files should be named `styles.ts`. As they are in their specific folders there is no reason to give them other names.

2023-06-07 13:07 UTC, danialsyed6 commented on src/api/todoApi.ts
> +  baseURL: "http://localhost:8000",
this should be in .env file

2023-06-07 13:07 UTC, danialsyed6 commented on src/api/todoApi.ts
> +  const response = await todoApi.get("/todos");
as this file is only for todo list you can add this to todoApi like `baseURL: '${BASE_URL}/todos'`

2023-06-07 13:07 UTC, danialsyed6 commented on src/components/TodoActions/index.tsx
> +import { schema } from "../../utils/data";
this should be named properly like `todoSchema`

2023-06-07 13:07 UTC, danialsyed6 commented on src/components/TodoActions/index.tsx
> +          </Button>
new and add values should change to edit as you select to edit todo

2023-06-07 13:07 UTC, danialsyed6 commented on src/components/TodoList/index.tsx
> +  }
braces are not required if there is only one line after the if or else statements

2023-06-07 13:07 UTC, danialsyed6 commented on src/components/TodoList/index.tsx
> +          <Box key={todo.id} sx={style.todoTaskBoxStyle}>
instead of this you can early return if there are no todos or use `todos?.map`

2023-06-07 13:07 UTC, danialsyed6 commented on src/components/TodoList/index.tsx
> +              {todo.todo}
use a better naming convention like `todo.task`

2023-06-07 13:07 UTC, danialsyed6 requested changes
your style files should be named `styles.ts`. As they are in their specific folders there is no reason to give them other names.

2023-06-09 06:29 UTC, danialsyed6 requested changes

2023-06-09 06:29 UTC, danialsyed6 commented on src/components/TodoActions/index.tsx
> +      {selectedTodo ? <EditTodo /> : <AddTodo />}
use single generic form to handle these cases

2023-06-09 06:31 UTC, danialsyed6 commented
pull main into your branch to resolve conflict.

2023-06-09 06:43 UTC, ahmadfaraz629 commented on src/api/todoApi.ts
> +export { getTodos, addTodo, deleteTodo, editTodo };
axios.create is using baseURL and each request is also talking baseURL. its redundent.

2023-06-09 06:43 UTC, ahmadfaraz629 commented on src/components/TodoActions/EditTodo.tsx
> +    console.log(getSelectedTodo());
remove console.log

2023-06-09 06:43 UTC, ahmadfaraz629 commented on src/store/todoController.ts
> +};
Its a good use of hookstate but we can manage it better.

Ask danial about the controller pattern.

2023-06-09 06:47 UTC, IshfaqAhmedAwan commented on src/components/TodoList/index.tsx
> +  console.log("todoList component");
remove the unnecessary consoles

2023-06-09 06:47 UTC, IshfaqAhmedAwan commented on src/components/TodoList/index.tsx
> +  };
name it more meaningful something like toggleCompletionHandler

2023-06-09 10:13 UTC, danialsyed6 approved these changes

2023-06-09 10:13 UTC, danialsyed6 commented on src/store/todoController.ts
> +    },
There’s a bug here I think

2023-06-09 10:43 UTC, ahmadfaraz629 approved these changes

2023-06-09 11:45 UTC, merged